config/routes.rb
Rails.application.routes.draw do
   root to: 'repositories#index'
   post '/repositories/update_trending', to: 'repositories#update_trending'  
   resources :repositories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/repository.rb
class Repository < ApplicationRecord
    #getting ruby trendings

  def self.update_trending_topics
    Repository.delete_all
    languages = ["ruby", "php", "python", "assembly", "java"]
    languages.each do |language|
      update_repositories(language)
    end
  end

  def self.update_repositories(language)
    url = "https://api.github.com/search/repositories?q=language:#{language}&sort=stars&order=desc&per_page=10"
    request = RestClient.get(url)
    @get_github_ruby= JSON.parse(request.body).with_indifferent_access[:items]
    @get_github_ruby.each do |subhash|
      repository = Repository.create(
        external_id: subhash[:id],
        name: subhash[:name],
        language: subhash[:language],
        owner_name: subhash[:owner][:login]
      )
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :set_repository, only: [:show, :edit, :update, :destroy]

  # GET /repositories
  # GET /repositories.json
  def index
    @repositories = Repository.all
  end

  # GET /repositories/1
  # GET /repositories/1.json
  def show
  end

#def get_repositories


#end
  # GET /repositories/new
  def new
    @repository = Repository.new
  end

  # GET /repositories/1/edit
  def edit
  end

  # POST /repositories
  # POST /repositories.json
  def create
    @repository = Repository.new(repository_params)

    respond_to do |format|
      if @repository.save
        format.html { redirect_to @repository, notice: 'Repository was successfully created.' }
        format.json { render :show, status: :created, location: @repository }
      else
        format.html { render :new }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
    end
  end
end

  # PATCH/PUT /repositories/1
  # PATCH/PUT /repositories/1.json
  def update
    respond_to do |format|
      if @repository.update(repository_params)
        format.html { redirect_to @repository, notice: 'Repository was successfully updated.' }
        format.json { render :show, status: :ok, location: @repository }
      else
        format.html { render :edit }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end
  

  # DELETE /repositories/1
  # DELETE /repositories/1.json
  def destroy
    @repository.destroy
    respond_to do |format|
      format.html { redirect_to repositories_url, notice: 'Repository was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update_trending 
    Repository.update_trending_topics
    redirect_to action: "index"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repository
      @repository = Repository.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repository_params
      params.require(:repository).permit(:external_id, :name, :owner_name, :language)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projetoateliware</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/repositories/_form.html.erb
<%= form_with(model: repository, local: true) do |form| %>
  <% if repository.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(repository.errors.count, "error") %> prohibited this repository from being saved:</h2>

      <ul>
      <% repository.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :external_id %>
    <%= form.number_field :external_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :owner_name %>
    <%= form.text_field :owner_name %>
  </div>

  <div class="field">
    <%= form.label :language %>
    <%= form.text_field :language %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/repositories/edit.html.erb
<h1>Editing Repository</h1>

<%= render 'form', repository: @repository %>

<%= link_to 'Show', @repository %> |
<%= link_to 'Back', repositories_path %>

app/views/repositories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Repositorios Destaques</h1>

<table border="1">
  <thead>
    <tr>
      <th>ID do projeto no GitHub</th>
      <th>Nome do projeto</th>
      <th>Nome do dono do projeto</th>
      <th>Linguagem</th>
      <th>Opções</th>
      <th colspan="3"></th>
    </tr>
  </thead>
        <%= button_to 'Buscar e armazenar repositorios', repositories_update_trending_path %>
  <tbody>
    <% @repositories.each do |repository| %>
      <tr>
        <td><%= repository.external_id %></td>
        <td><%= repository.name %></td>
        <td><%= repository.owner_name %></td>
        <td><%= repository.language %></td>
        <td><%= link_to 'Detalhes', repository%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/repositories/new.html.erb
<h1>New Repository</h1>

<%= render 'form', repository: @repository %>

<%= link_to 'Back', repositories_path %>

app/views/repositories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>External:</strong>
  <%= @repository.external_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @repository.name %>
</p>

<p>
  <strong>Owner name:</strong>
  <%= @repository.owner_name %>
</p>

<p>
  <strong>Language:</strong>
  <%= @repository.language %>
</p>

<%= link_to 'Edit', edit_repository_path(@repository) %> |
<%= link_to 'Back', repositories_path %>